<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\BackgroundJobs.Core\BackgroundJobs.Core.csproj" />
    <ProjectReference Include="..\..\src\BackgroundJobs.Storage.InMemory\BackgroundJobs.Storage.InMemory.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
</Project>
