<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    
    <ProjectReference Include="..\BackgroundJobs\BackgroundJobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <PropertyGroup>
    
    
    
  </PropertyGroup>

</Project>
