<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\BackgroundJobs\BackgroundJobs.csproj" />
    <ProjectReference Include="..\BackgroundJobs.Storage.PostgreSQL\BackgroundJobs.Storage.PostgreSQL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    
    
    
  </PropertyGroup>

</Project>
